postgres:
  image: postgres:9.3

redis:
  image: redis:2.6

# To add cassandra
# - Uncomment this configuration
# - Uncomment cassandra line in 'web' below
# - Uncomment configuration in config/cassandra.yml
# - See config/cassandra.yml.example for further setup instructions
# cassandra:
#   image: cassandra:2.2
#   environment:
#     CASSANDRA_START_RPC: 'true'

consul:
  image: gliderlabs/consul-server:0.5
  command: -node canvas-consul -bootstrap
  environment:
    GOMAXPROCS: "2"

kinesis:
  image: instructure/kinesalite
  environment:
    VIRTUAL_HOST: kinesis.docker
    VIRTUAL_PORT: 4567

web: &WEB
  build: .
  volumes:
    - "canvas-gems:/home/docker/.gem/ruby/2.1.0"
    - ".:/usr/src/app"
  links:
    - consul
    - postgres
    - redis
#    - cassandra
#    - selenium
    - kinesis
  environment:
    RACK_ENV: development
    VIRTUAL_HOST: .canvas.docker

jobs:
  <<: *WEB
  command: bundle exec script/delayed_job run
