canvas-postgres:
  image: postgres:9.3
  volumes:
    - "./pg_data:/var/lib/postgresql/data"

canvas-redis:
  image: redis:2.6

# To add cassandra
# - Uncomment this configuration
# - Uncomment cassandra line in 'web' below
# - Uncomment configuration in config/cassandra.yml
# - See config/cassandra.yml.example for further setup instructions
# canvas-cassandra:
#   image: cassandra:2.2
#   environment:
#     CASSANDRA_START_RPC: 'true'

canvas-consul:
  image: gliderlabs/consul-server:0.5
  command: -node canvas-consul -bootstrap
  environment:
    GOMAXPROCS: "2"

canvas-kinesis:
  image: instructure/kinesalite
  environment:
    VIRTUAL_HOST: kinesis.docker
    VIRTUAL_PORT: 4567

canvas-web: &WEB
  image: gimme-dat-canvas
  links:
    - canvas-consul
    - canvas-postgres
    - canvas-redis
#    - canvas-cassandra
    - canvas-kinesis
  environment:
    RACK_ENV: development
    VIRTUAL_HOST: canvas.docker

canvas-jobs:
  <<: *WEB
  command: bundle exec script/delayed_job run
